# Generated by Django 4.2 on 2023-05-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_goal_match_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GoalKeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Mid', 'Midfielder'), ('Forward', 'Forward')], max_length=20),
        ),
    ]
